Repository smartcontractkit/ea-framework-js, pull requests merged in 2022-12, with the labels that each got.

#2 Update to latest changes
  package.json
  src/adapter/basic.ts
  src/config/index.ts
  src/index.ts
  src/util/logger.ts
  src/validation/utils.ts
  test/config.test.ts
  test/transports/websocket.test.ts
  test/validation.test.ts
Labels: chore, patch

#1 Feature/Custom input validation
  .gitignore
  package.json
  src/adapter/basic.ts
  src/adapter/endpoint.ts
  src/adapter/types.ts
  src/config/index.ts
  src/validation/index.ts
  test/validation.test.ts
  yarn.lock
Labels: feature, minor

#6 Fix/Handle circular references when censoring logs
  src/util/logger.ts
  test/logger.test.ts
Labels: patch, hotfix

#12 Chore/Version drift
  package.json
Labels: chore, patch

#14 add validation for input overrides
  src/validation/input-validator.ts
  src/validation/utils.ts
  test/validation.test.ts
Labels: feature, minor

#11 Fix/Config number parsing
  src/config/index.ts
  test/config.test.ts
Labels: patch, hotfix

#19 Small requester fix
  docs/porting-a-v2-ea-to-v3.md
  src/transports/http.ts
  src/util/requester.ts
  test/index.test.ts
Labels: chore, patch
