Repository smartcontractkit/ea-framework-js, pull requests merged in 2023-05, with the labels that each got.

#172 fix bug with empty coverage branch
  .github/workflows/main.yaml
Labels: none

#175 PDI-32: Add step to version bump PR workflow to add generated docs
  .github/workflows/open-version-bump-pr.yaml
  README.md
  package.json
Labels: patch

#176 patch/PDI-2106: Change WS closing status to 1000
  src/transports/websocket.ts
  test/transports/websocket.test.ts
Labels: patch

#178 Tweak ref tables
  docs/reference-tables/ea-settings.md
  docs/reference-tables/metrics.md
  scripts/ea-settings-table.ts
  scripts/metrics-table.ts
Labels: none

#177 patch/PDI-2104: getMetrics method now accesses metrics directly
  test/util.ts
Labels: patch

#180 add array util functions
  docs/reference-tables/ea-settings.md
  docs/reference-tables/metrics.md
  src/util/index.ts
  test/utils.test.ts
Labels: patch

#181 format ref tables
  package.json
Labels: none

#183 change the logic of version-bump pr workflow
  .github/WORKFLOW-README.MD
  .github/workflows/open-version-bump-pr.yaml
Labels: patch

#185 PDI-63: Add startup check to verify that cache type is shareable when not setting EA to RW
  src/adapter/basic.ts
  test/index.test.ts
Labels: patch

#187 move test utils to src
  src/util/testing-utils.ts
  test/adapter.test.ts
  test/background-executor.test.ts
  test/cache/cache-key.test.ts
  test/cache/helper.ts
  test/cache/local.test.ts
  test/cache/redis.test.ts
  test/cache/response-cache.test.ts
  test/correlation.test.ts
  test/error.test.ts
  test/index.test.ts
  test/logger.test.ts
  test/metrics/metrics.test.ts
  test/metrics/polling-metrics.test.ts
  test/metrics/redis-metrics.test.ts
  test/metrics/warmer-metrics.test.ts
  test/metrics/ws-metrics.test.ts
  test/overrides.test.ts
  test/price.test.ts
  test/rate-limit-config.test.ts
  test/subscription-set/redis-subscription-set.test.ts
  test/subscription-set/subscription-set-factory.test.ts
  test/transports/http.test.ts
  test/transports/routing.test.ts
  test/transports/sse.test.ts
  test/transports/websocket.test.ts
  test/validation.test.ts
Labels: patch

#188 PDI-2153: Enable TLS
  src/config/index.ts
  src/index.ts
  src/metrics/index.ts
  test/index.test.ts
Labels: minor

#189 (workaround) Put logs that would expose the input parameters object behind a feature flag
  src/adapter/basic.ts
  src/background-executor.ts
  src/cache/index.ts
  src/cache/local.ts
  src/cache/redis.ts
  src/cache/response.ts
  src/config/index.ts
  src/index.ts
  src/metrics/index.ts
  src/transports/abstract/streaming.ts
  src/transports/abstract/subscription.ts
  src/transports/http.ts
  src/transports/websocket.ts
  src/util/logger.ts
  src/util/requester.ts
  src/validation/index.ts
Labels: patch
