Repository smartcontractkit/ea-framework-js, pull requests merged in 2023-02, with the labels that each got.

#55 Fix calc mistake on cache max age
  src/config/index.ts
Labels: patch, hotfix

#53 Add CryptoPriceEndpoint class
  src/adapter/price.ts
  test/price.test.ts
Labels: feature, minor

#58 Add adapter name to cache key
  src/adapter/basic.ts
  src/adapter/endpoint.ts
  src/cache/index.ts
  src/cache/response.ts
  src/transports/metrics.ts
  src/validation/index.ts
  test/cache/cache-key.test.ts
  test/cache/helper.ts
  test/cache/redis.test.ts
  test/metrics/metrics.test.ts
Labels: patch, hotfix

#43 Create New v3 EA guide
  README.md
  docs/creating-a-new-v3-ea.md
  docs/porting-a-v2-ea-to-v3.md
  docs/v3-ea-components/adapter.md
  docs/v3-ea-components/endpoints.md
  docs/v3-ea-components/tests.md
  docs/v3-ea-components/transport-types/custom-transport.md
  docs/v3-ea-components/transport-types/http-transport.md
  docs/v3-ea-components/transport-types/sse-transport.md
  docs/v3-ea-components/transport-types/websocket-transport.md
  docs/v3-ea-components/transports.md
Labels: docs, none

#60 Add endpoint name to http request queue key
  src/cache/index.ts
  src/transports/http.ts
  test/transports/http.test.ts
Labels: patch, hotfix

#62 Fix excessive debug/trace logging
  src/adapter/basic.ts
  src/config/provider-limits.ts
  src/transports/websocket.ts
  test/metrics/ws-metrics.test.ts
  test/transports/http.test.ts
  test/transports/websocket.test.ts
Labels: patch, hotfix

#63 Add transport input parameter for routing transport
  src/adapter/endpoint.ts
  src/adapter/types.ts
  src/transports/meta/routing.ts
  src/util/types.ts
  src/validation/index.ts
  src/validation/input-params.ts
  test/metrics/ws-metrics.test.ts
  test/price.test.ts
  test/transports/routing.test.ts
  test/transports/sse.test.ts
  test/transports/websocket.test.ts
  test/util.ts
Labels: feature, minor

#70 Add docs for Routing transport, update README
  README.md
  docs/v3-ea-components/transport-types/routing-transport.md
  docs/v3-ea-components/transports.md
Labels: patch

#72 Fix publish workflow
  .github/workflows/publish.yaml
Labels: patch

#76 fix pinned deps pipeline
  .github/workflows/pinned-dependencies.yaml
Labels: none

#74 Add test utilities, refactor
  .eslintrc.js
  src/background-executor.ts
  src/index.ts
  src/metrics/index.ts
  src/transports/http.ts
  src/transports/websocket.ts
  src/util/requester.ts
  src/validation/error.ts
  test/background-executor.test.ts
  test/cache/cache-key.test.ts
  test/cache/helper.ts
  test/cache/local.test.ts
  test/cache/redis.test.ts
  test/correlation.test.ts
  test/error.test.ts
  test/index.test.ts
  test/logger.test.ts
  test/metrics/helper.ts
  test/metrics/metrics.test.ts
  test/metrics/polling-metrics.test.ts
  test/metrics/redis-metrics.test.ts
  test/metrics/warmer-metrics.test.ts
  test/metrics/ws-metrics.test.ts
  test/overrides.test.ts
  test/price.test.ts
  test/rate-limit-config.test.ts
  test/subscription-set/redis-subscription-set.test.ts
  test/transports/http.test.ts
  test/transports/routing.test.ts
  test/transports/sse.test.ts
  test/transports/websocket.test.ts
  test/util.ts
  test/validation.test.ts
Labels: minor

#75 remove smoke endpoint
  docs/v3-ea-components/adapter.md
  src/config/index.ts
  src/index.ts
  src/util/test-payload-loader.ts
  test/smoke/smoke.test.ts
  test/smoke/test-payload-fail.json
  test/smoke/test-payload.js
  test/smoke/test-payload.json
Labels: minor

#78 Remove nock, bump axios, fix error logging
  package.json
  src/transports/http.ts
  src/validation/index.ts
  test/config.test.ts
  test/metrics/metrics.test.ts
  test/metrics/polling-metrics.test.ts
  test/metrics/warmer-metrics.test.ts
  test/subscription-set/redis-subscription-set.test.ts
  test/transports/http.test.ts
  test/transports/routing.test.ts
  test/transports/sse.test.ts
  yarn.lock
Labels: patch

#79 Update max key length logic
  src/cache/index.ts
  test/cache/cache-key.test.ts
Labels: patch

#80 replace axios with requester for sse transport
  src/transports/sse.ts
Labels: minor

#82 Remove defaultTransport parameter from RoutingTransport
  docs/v3-ea-components/transport-types/routing-transport.md
  src/transports/meta/routing.ts
  test/transports/routing.test.ts
Labels: patch

#83 Add background execute errors metric, transport label, more
  package.json
  src/background-executor.ts
  src/config/provider-limits.ts
  src/metrics/index.ts
  src/rate-limiting/index.ts
  src/util/logger.ts
  src/util/requester.ts
  test/background-executor.test.ts
  test/metrics/metrics.test.ts
  test/metrics/polling-metrics.test.ts
  test/metrics/redis-metrics.test.ts
  test/metrics/warmer-metrics.test.ts
  test/metrics/ws-metrics.test.ts
  test/util.ts
  yarn.lock
Labels: patch
