Repository smartcontractkit/ea-framework-js, pull requests merged in 2023-01, with the labels that each got.

#24 Chore/Version sync
  package.json
Labels: minor, chore

#20 Enforce right type for adapter config in routing transport
  src/transports/meta/routing.ts
Labels: feature, minor

#23 Treat literal "" env var values as empty
  src/config/index.ts
Labels: patch, hotfix

#28 Revert websocket message param change
  src/transports/websocket.ts
Labels: patch, hotfix

#22 Feature/Replace cache key with stringified params
  src/cache/index.ts
  src/transports/abstract/subscription.ts
  src/util/subscription-set/expiring-sorted-set.ts
  src/util/subscription-set/redis-sorted-set.ts
  src/util/subscription-set/subscription-set.ts
  test/cache/cache-key.test.ts
  test/cache/helper.ts
  test/metrics/feed-id.test.ts
  test/metrics/labels.test.ts
  test/metrics/metrics.test.ts
  test/metrics/ws-metrics.test.ts
Labels: feature, minor

#18 Feature/Add limit to subscription set
  src/cache/local.ts
  src/config/index.ts
  src/transports/abstract/subscription.ts
  src/util/index.ts
  src/util/subscription-set/expiring-sorted-set.ts
  src/util/subscription-set/redis-sorted-set.ts
  src/util/subscription-set/subscription-set.ts
  test/subscription-set/subscription-set-factory.test.ts
Labels: feature, minor

#32 enforce SingleNumberResultResponse for PriceEndpoint
  src/adapter/price.ts
  src/adapter/types.ts
Labels: feature, patch

#35 Feature/Consolidate metrics into class
  package.json
  src/adapter/basic.ts
  src/background-executor.ts
  src/cache/metrics.ts
  src/cache/redis.ts
  src/index.ts
  src/metrics/index.ts
  src/rate-limiting/metrics.ts
  src/transports/abstract/subscription.ts
  src/transports/http.ts
  src/transports/metrics.ts
  src/transports/websocket.ts
  src/util/metrics.ts
  src/util/requester.ts
  test/metrics/labels.test.ts
  test/metrics/metrics.test.ts
Labels: feature, minor

#37 Add WebsocketTransport wrapper with reverse mapping
  src/transports/websocket.ts
  test/transports/websocket.test.ts
Labels: feature, minor

#40 Update ea v2 to v3 migration guide
  docs/porting-a-v2-ea-to-v3.md
Labels: feature, minor

#38 Clarify ingestion timestamp format
  docs/porting-a-v2-ea-to-v3.md
  src/adapter/basic.ts
  src/cache/redis.ts
  src/cache/response.ts
  src/transports/http.ts
  src/transports/sse.ts
  src/transports/websocket.ts
  src/util/requester.ts
  src/util/types.ts
  test/cache/cache-key.test.ts
  test/cache/helper.ts
  test/cache/local.test.ts
  test/error.test.ts
  test/metrics/metrics.test.ts
  test/overrides.test.ts
  test/price.test.ts
  test/util.ts
Labels: feature, minor

#44 Change log to use correct env var
  src/transports/sse.ts
Labels: patch, hotfix

#42 Initialize metrics earlier
  src/adapter/basic.ts
  src/index.ts
Labels: patch, hotfix

#45 Improve performance on streaming subscription sets
  src/transports/abstract/streaming.ts
Labels: patch, improvement

#49 Fix inverse data issue
  src/adapter/basic.ts
  src/adapter/price.ts
  src/cache/index.ts
  src/cache/local.ts
  src/cache/redis.ts
  src/cache/response.ts
  test/util.ts
Labels: patch, hotfix

#52 Export ProviderRequestConfig & WebsocketTransportGenerics
  src/transports/http.ts
  src/transports/websocket.ts
Labels: feature, minor
