Repository smartcontractkit/ea-framework-js, pull requests merged in 2023-08, with the labels that each got.

#216 Cache lock fix: deferring lock acquisition
  src/adapter/basic.ts
  src/cache/redis.ts
  src/config/index.ts
  src/index.ts
  src/util/testing-utils.ts
  test/cache/cache-lock.test.ts
  test/index.test.ts
Labels: patch

#215 Subclasses for PoR adapters
  src/adapter/por.ts
  src/config/index.ts
  test/por.ts
Labels: minor

#95 add docs for http transport
  docs/components/transport-types/http-transport.md
Labels: none

#98 add docs for ws transport
  docs/components/transport-types/websocket-transport.md
Labels: none

#101 add docs for sse transport
  docs/components/transport-types/http-transport.md
  docs/components/transport-types/sse-transport.md
  docs/components/transport-types/websocket-transport.md
Labels: none

#107 add docs for custom transport
  docs/components/transport-types/custom-transport.md
Labels: none

#222 Add local cache to redis
  src/cache/factory.ts
  src/cache/redis.ts
  test/cache/cache-lock.test.ts
  test/cache/redis.test.ts
  test/index.test.ts
  test/metrics/redis-metrics.test.ts
Labels: patch

#224 Add API_TIMEOUT default to the PoR adapter subclass
  src/adapter/por.ts
Labels: patch

#226 add examples to input parameters
  src/validation/input-params.ts
  test/validation.test.ts
Labels: patch

#208 fix ref tables generation workflow
  .github/workflows/open-version-bump-pr.yaml
Labels: patch

#227 Remove version bump check
  .github/workflows/validate-version-bump-pr.yaml
Labels: none

#211 update github workflow docs
  .github/WORKFLOW-README.MD
  docs/github_workflows.md
Labels: none

#229 add input examples to ea generator
  scripts/generator-adapter/generators/app/templates/src/endpoint/base.ts.ejs
Labels: patch

#228 Provide WebSocket options func with desired subscriptions
  src/transports/websocket.ts
Labels: minor

#231 Add CACHE_MAX_AGE default to the PoR subclass
  src/adapter/por.ts
Labels: patch
