Repository smartcontractkit/ea-framework-js, pull requests merged in 2023-04, with the labels that each got.

#126 add new testcases for WS connection
  src/config/index.ts
  src/transports/websocket.ts
  test/transports/websocket.test.ts
Labels: patch

#121 Add TIME_TO_SLEEP_MS to BaseSettingsDefinition
  src/config/index.ts
  src/util/requester.ts
Labels: minor

#134 add missing tests to increase test coverage
  src/adapter/basic.ts
  src/adapter/endpoint.ts
  src/cache/response.ts
  src/transports/websocket.ts
  src/validation/index.ts
  test/adapter.test.ts
  test/cache/cache-key.test.ts
  test/cache/helper.ts
  test/cache/redis.test.ts
  test/config.test.ts
  test/error.test.ts
  test/index.test.ts
  test/metrics/metrics.test.ts
  test/price.test.ts
  test/rate-limit-config.test.ts
  test/subscription-set/subscription-set-factory.test.ts
  test/transports/routing.test.ts
  test/transports/sse.test.ts
  test/transports/websocket.test.ts
  test/validation.test.ts
Labels: patch

#136 Calculate feed ID after overriden values to make it consistent
  src/config/index.ts
  src/validation/index.ts
Labels: patch

#138 add gh workflow step to check for test.only()
  .github/workflows/main.yaml
Labels: none

#137 lint and prettier test files
  .eslintignore
  package.json
  test/transports/routing.test.ts
  test/transports/websocket.test.ts
  test/util.ts
  test/validation.test.ts
Labels: none

#129 censor sensitive values when writing to response cache
  src/cache/response.ts
  src/util/logger.ts
  test/cache/response-cache.test.ts
  test/index.test.ts
  test/validation.test.ts
Labels: patch

#140 Update custom script to avoid using redis functions
  src/cache/redis.ts
  test/cache/response-cache.test.ts
  test/index.test.ts
  test/util.ts
Labels: patch

#141 PDI 2010 - Added rate limit config validations for non-positive numbers in v3 framework
  src/adapter/basic.ts
  test/rate-limit-config.test.ts
Labels: patch

#144 PDI-2073: Add adapter name to EA response
  src/cache/response.ts
  src/util/types.ts
  test/cache/response-cache.test.ts
  test/metrics/metrics.test.ts
Labels: patch

#145 Add more details to unhandled promise message
  src/index.ts
Labels: patch

#146 warn when saving undefined to response cache
  src/cache/response.ts
Labels: patch

#147 Fix undefined data warn
  src/cache/response.ts
Labels: patch

#149 Adjust response timestamp validator to account for clock drift
  src/validation/utils.ts
  test/validation.test.ts
Labels: patch

#151 Refactor Input parameters
  docs/porting-a-v2-ea-to-v3.md
  docs/v3-ea-components/adapter.md
  docs/v3-ea-components/endpoints.md
  package.json
  src/adapter/basic.ts
  src/adapter/endpoint.ts
  src/adapter/price.ts
  src/adapter/types.ts
  src/cache/index.ts
  src/cache/response.ts
  src/config/index.ts
  src/metrics/index.ts
  src/metrics/util.ts
  src/transports/abstract/streaming.ts
  src/transports/abstract/subscription.ts
  src/transports/http.ts
  src/transports/index.ts
  src/transports/metrics.ts
  src/transports/sse.ts
  src/transports/websocket.ts
  src/util/index.ts
  src/util/logger.ts
  src/util/types.ts
  src/validation/index.ts
  src/validation/input-params.ts
  src/validation/input-validator.ts
  src/validation/utils.ts
  test/adapter.test.ts
  test/background-executor.test.ts
  test/cache/cache-key.test.ts
  test/cache/helper.ts
  test/cache/local.test.ts
  test/cache/redis.test.ts
  test/cache/response-cache.test.ts
  test/correlation.test.ts
  test/error.test.ts
  test/index.test.ts
  test/logger.test.ts
  test/metrics/feed-id.test.ts
  test/metrics/helper.ts
  test/metrics/labels.test.ts
  test/metrics/metrics.test.ts
  test/metrics/redis-metrics.test.ts
  test/metrics/ws-metrics.test.ts
  test/overrides.test.ts
  test/price.test.ts
  test/rate-limit-config.test.ts
  test/subscription-set/redis-subscription-set.test.ts
  test/transports/http.test.ts
  test/transports/routing.test.ts
  test/transports/sse.test.ts
  test/transports/websocket.test.ts
  test/util.ts
  test/validation.test.ts
  yarn.lock
Labels: minor

#154 Fix input params refactor types
  src/adapter/basic.ts
  src/adapter/price.ts
  src/index.ts
  src/metrics/index.ts
  src/util/logger.ts
  src/util/types.ts
  src/validation/index.ts
Labels: patch

#156 Add smarter typing to optioned input params
  src/validation/input-params.ts
  test/validation.test.ts
Labels: patch

#158 Fix logger censor
  src/util/logger.ts
  test/logger.test.ts
Labels: patch

#160 Fix price test types
  src/adapter/price.ts
  src/adapter/types.ts
  src/validation/input-params.ts
  test/price.test.ts
Labels: patch

#162 Fix crypto price endpoint
  src/adapter/price.ts
  test/price.test.ts
Labels: patch

#165 Fix generic adapter requests in endpoint parameters
  src/adapter/basic.ts
  src/adapter/endpoint.ts
  src/adapter/price.ts
  src/adapter/types.ts
  src/index.ts
  src/metrics/index.ts
  src/transports/abstract/subscription.ts
  src/transports/index.ts
  src/util/logger.ts
  src/util/types.ts
  src/validation/index.ts
  src/validation/input-params.ts
  test/cache/helper.ts
  test/cache/response-cache.test.ts
  test/overrides.test.ts
  test/price.test.ts
  test/util.ts
  test/validation.test.ts
Labels: patch

#167 Fix input validator 0 defaults
  src/validation/input-params.ts
  test/validation.test.ts
Labels: patch

#169 Request data object validation
  src/validation/index.ts
  test/util.ts
  test/validation.test.ts
Labels: patch

#153 add badges to readme
  .c8rc.json
  .github/workflows/main.yaml
  .github/workflows/open-version-bump-pr.yaml
  README.md
Labels: patch
