Repository smartcontractkit/ea-framework-js, pull requests merged in 2023-03, with the labels that each got.

#86 Refactor transport routing
  README.md
  docs/porting-a-v2-ea-to-v3.md
  docs/v3-ea-components/transport-types/routing-transport.md
  docs/v3-ea-components/transports.md
  src/adapter/basic.ts
  src/adapter/endpoint.ts
  src/adapter/price.ts
  src/adapter/types.ts
  src/background-executor.ts
  src/cache/index.ts
  src/cache/response.ts
  src/transports/abstract/subscription.ts
  src/transports/http.ts
  src/transports/index.ts
  src/transports/meta/index.ts
  src/transports/meta/routing.ts
  src/transports/sse.ts
  src/transports/websocket.ts
  src/util/types.ts
  src/validation/index.ts
  src/validation/input-params.ts
  test/background-executor.test.ts
  test/cache/cache-key.test.ts
  test/cache/helper.ts
  test/metrics/metrics.test.ts
  test/metrics/warmer-metrics.test.ts
  test/metrics/ws-metrics.test.ts
  test/overrides.test.ts
  test/price.test.ts
  test/transports/http.test.ts
  test/transports/routing.test.ts
  test/util.ts
  test/validation.test.ts
Labels: minor

#88 Mark priceMeta as optional
  src/adapter/price.ts
  test/price.test.ts
Labels: patch, hotfix

#90 Refactor Settings
  src/adapter/basic.ts
  src/adapter/endpoint.ts
  src/adapter/price.ts
  src/adapter/types.ts
  src/background-executor.ts
  src/cache/index.ts
  src/cache/response.ts
  src/config/index.ts
  src/index.ts
  src/metrics/index.ts
  src/metrics/util.ts
  src/rate-limiting/index.ts
  src/transports/abstract/subscription.ts
  src/transports/http.ts
  src/transports/index.ts
  src/transports/metrics.ts
  src/transports/sse.ts
  src/transports/websocket.ts
  src/util/logger.ts
  src/util/requester.ts
  src/util/subscription-set/subscription-set.ts
  src/validation/index.ts
  test/background-executor.test.ts
  test/cache/cache-key.test.ts
  test/cache/local.test.ts
  test/cache/redis.test.ts
  test/config.test.ts
  test/index.test.ts
  test/logger.test.ts
  test/metrics/feed-id.test.ts
  test/metrics/helper.ts
  test/metrics/labels.test.ts
  test/metrics/metrics.test.ts
  test/metrics/polling-metrics.test.ts
  test/metrics/redis-metrics.test.ts
  test/metrics/warmer-metrics.test.ts
  test/metrics/ws-metrics.test.ts
  test/price.test.ts
  test/rate-limit-config.test.ts
  test/subscription-set/redis-subscription-set.test.ts
  test/subscription-set/subscription-set-factory.test.ts
  test/transports/http.test.ts
  test/transports/routing.test.ts
  test/transports/sse.test.ts
  test/transports/websocket.test.ts
  test/util.ts
  test/validation.test.ts
Labels: minor

#92 Refactor transport routes
  src/adapter/basic.ts
  src/adapter/endpoint.ts
  src/adapter/types.ts
  src/background-executor.ts
  src/transports/index.ts
  test/transports/routing.test.ts
Labels: minor

#96 Add background execute and websocket open timeouts
  src/background-executor.ts
  src/config/index.ts
  src/metrics/index.ts
  src/transports/websocket.ts
  src/util/index.ts
  test/background-executor.test.ts
  test/transports/websocket.test.ts
Labels: patch

#93 Fix settings generics in adapter
  package.json
  src/adapter/basic.ts
  src/adapter/price.ts
  src/adapter/types.ts
  src/config/index.ts
  src/index.ts
  test/transports/routing.test.ts
  test/util.ts
Labels: patch

#99 Connection parameter fix
  src/transports/websocket.ts
Labels: patch

#103 Remove add labels workflow
  .github/workflows/add-or-validate-labels.yaml
Labels: none

#102 Reorganize WebSocket listeners
  docs/v3-ea-components/tests.md
  src/transports/websocket.ts
  src/util/index.ts
  test/background-executor.test.ts
  test/metrics/ws-metrics.test.ts
  test/transports/routing.test.ts
  test/transports/websocket.test.ts
  test/util.ts
Labels: patch

#108 Re add rate limiting strategies, fix tests & simple counting
  .github/workflows/add-or-validate-labels.yaml
  src/adapter/basic.ts
  src/config/index.ts
  src/metrics/index.ts
  src/rate-limiting/burst.ts
  src/rate-limiting/factory.ts
  src/rate-limiting/fixed-interval.ts
  src/rate-limiting/index.ts
  src/transports/websocket.ts
  src/util/requester.ts
  test/metrics/metrics.test.ts
  test/metrics/warmer-metrics.test.ts
  test/rate-limit-config.test.ts
  test/transports/http.test.ts
  test/transports/websocket.test.ts
  test/util.ts
Labels: patch

#110 Add transport name and metrics to redis subscription set
  src/cache/metrics.ts
  src/cache/redis.ts
  src/metrics/index.ts
  src/transports/abstract/subscription.ts
  src/util/subscription-set/redis-sorted-set.ts
  src/util/subscription-set/subscription-set.ts
  src/validation/index.ts
  test/subscription-set/redis-subscription-set.test.ts
  test/subscription-set/subscription-set-factory.test.ts
Labels: patch

#112 Fix rate limit warn, update fastify
  package.json
  src/adapter/basic.ts
  yarn.lock
Labels: patch

#114 Fix requester retries
  src/util/requester.ts
  test/transports/http.test.ts
Labels: patch

#109 validate user provided timestamp
  src/cache/response.ts
  src/transports/abstract/streaming.ts
  src/validation/utils.ts
  test/validation.test.ts
Labels: patch

#116 add unhandledRejection handler
  src/index.ts
Labels: patch

#118 Add transport name to background metrics
  src/metrics/index.ts
  src/transports/abstract/subscription.ts
  test/metrics/warmer-metrics.test.ts
  test/metrics/ws-metrics.test.ts
Labels: patch

#119 skip overwriting successful cache entries with errors
  src/cache/local.ts
  src/cache/redis.ts
  test/cache/local.test.ts
  test/metrics/redis-metrics.test.ts
  test/util.ts
Labels: minor

#124 Fix resubscribes on server side ws connection closures
  src/transports/websocket.ts
  test/transports/websocket.test.ts
Labels: patch

#120 enforce uppercase ea name
  src/adapter/basic.ts
  test/adapter.test.ts
Labels: patch

#117 Add ability to override endpoint name in requester key
  src/transports/http.ts
  test/transports/http.test.ts
  test/util.ts
Labels: patch
